export const ACCESS_TOKEN_HEADER_NAME = 'jwt';
export const ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET';
export const ACCESS_TOKEN_EXPIRATION_TIME = 'ACCESS_TOKEN_EXPIRATION_TIME';

export const REFRESH_TOKEN_HEADER_NAME = 'jwt-refresh';
export const REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET';
export const REFRESH_TOKEN_EXPIRATION_TIME = 'REFRESH_TOKEN_EXPIRATION_TIME';

