export const HOST = 'HOST';
export const PORT = 'PORT';
export const GLOBAL_PREFIX = 'auto-repair-api';
export const NODE_ENV = 'development';
export const NODE_ENV_PROD = 'production';
export const NODE_ENV_PRE = 'preproduction';
export const NODE_ENV_DEV = 'development';

export const AXIOS_HTTP_TIMEOUT = 'AXIOS_HTTP_TIMEOUT';
export const AXIOS_HTTP_MAX_REDIRECTS = 'AXIOS_HTTP_MAX_REDIRECTS';

export const ACCESS_TOKEN_HEADER_NAME = 'jwt';
export const ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET';
export const ACCESS_TOKEN_EXPIRATION_TIME = 'ACCESS_TOKEN_EXPIRATION_TIME';

export const REFRESH_TOKEN_HEADER_NAME = 'jwt-refresh';
export const REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET';
export const REFRESH_TOKEN_EXPIRATION_TIME = 'REFRESH_TOKEN_EXPIRATION_TIME';

export const USER_ID_HASH_CONFIG = 'USER_ID_HASH_CONFIG';
export const USER_ID_HASH_SALT = 'USER_ID_HASH_SALT';

export const USER_PASS_HASH_CONFIG = 'USER_PASS_HASH_CONFIG';
export const USER_PASS_HASH_SALT = 'USER_PASS_HASH_SALT';

export const AZURE_INSIGHTS_CONNECTION = 'AZURE_INSIGHTS_CONNECTION';
export const AZURE_MONGO_CONNECTION = 'AZURE_MONGO_CONNECTION';

export const AZURE_REDIS_HOST = 'AZURE_REDIS_HOST';
export const AZURE_REDIS_PORT = 'AZURE_REDIS_PORT';
export const AZURE_REDIS_AUTH_PASS = 'AZURE_REDIS_AUTH_PASS';
export const AZURE_REDIS_TLS_HOST = 'AZURE_REDIS_TLS_HOST';

export const DATABASE_POSTGRES_TYPE = 'DATABASE_POSTGRES_TYPE';
export const DATABASE_POSTGRES_HOST = 'DATABASE_POSTGRES_HOST';
export const DATABASE_POSTGRES_PORT = 'DATABASE_POSTGRES_PORT';
export const DATABASE_POSTGRES_NAME = 'DATABASE_POSTGRES_NAME';
export const DATABASE_POSTGRES_USERNAME = 'DATABASE_POSTGRES_USERNAME';
export const DATABASE_POSTGRES_PASS = 'DATABASE_POSTGRES_PASS';
export const DATABASE_POSTGRES_SSL = 'DATABASE_POSTGRES_SSL';
